src/main/java/com/moa/domain/interests/Interests.java
src/main/java/com/moa/domain/interests/InterestsRepository.java
src/main/java/com/moa/domain/user/User.java
src/main/java/com/moa/domain/user/UserRepository.java

#2 
- User
- Interests
- UserRepository
- InterestsRepository

#2 feat: User, Interests 엔티티 매핑

---

src/main/java/com/moa/domain/member/ApplimentMember.java
src/main/java/com/moa/domain/member/Approval.java
src/main/java/com/moa/domain/member/RecruitMember.java
src/main/java/com/moa/domain/notice/Notice.java
src/main/java/com/moa/domain/notice/NoticeRepository.java
src/main/java/com/moa/domain/notice/Post.java
src/main/java/com/moa/domain/possible/PossibleTime.java
src/main/java/com/moa/domain/possible/PossibleTimeSelector.java
src/main/java/com/moa/domain/possible/PossibleTimeSelectorRepository.java
src/main/java/com/moa/domain/recruit/RecruitState.java
src/main/java/com/moa/domain/recruit/Recruitment.java
src/main/java/com/moa/domain/recruit/RecruitmentRepository.java

feat: 전체 Entity 매핑

---

build.gradle
src/main/java/com/moa/controller/UserController.java
src/main/java/com/moa/domain/user/User.java
src/main/java/com/moa/domain/user/UserRepository.java
src/main/java/com/moa/dto/user/UserSignupRequest.java
src/main/java/com/moa/global/auth/model/SecurityUser.java
src/main/java/com/moa/global/auth/model/TokenMapping.java
src/main/java/com/moa/global/auth/utils/JwtService.java
src/main/java/com/moa/global/config/ApplicationRunnerConfig.java
src/main/java/com/moa/global/config/SecurityBeanConfig.java
src/main/java/com/moa/global/config/SecurityConfig.java
src/main/java/com/moa/global/filter/JwtAuthorizationFilter.java
src/main/java/com/moa/global/filter/LoginProcessFilter.java
src/main/java/com/moa/global/filter/handler/JwtProviderHandler.java
src/main/java/com/moa/service/UserService.java
src/main/resources/application.yml

#4 
- 로그인
- JWT 발행
- JWT 인증
- 회원 가입

#4 Feat jhs 4

---

src/main/java/com/moa/controller/LoginArgumentResolver.java
src/main/java/com/moa/controller/UserController.java
src/main/java/com/moa/domain/user/User.java
src/main/java/com/moa/dto/user/Login.java
src/main/java/com/moa/dto/user/UserInfoResponse.java
src/main/java/com/moa/dto/user/UserLogin.java
src/main/java/com/moa/dto/user/UserUpdateRequest.java
src/main/java/com/moa/global/auth/utils/JwtService.java
src/main/java/com/moa/global/config/WebConfig.java
src/main/java/com/moa/service/UserService.java
src/test/java/com/moa/service/UserServiceTest.java

#3 feat: 사용자 관련 기능

---

.gitignore
src/docs/asciidoc/index.adoc
src/main/java/com/moa/dto/user/UserSignupRequest.java
src/main/java/com/moa/global/config/SecurityConfig.java
src/main/java/com/moa/global/exception/GlobalControllerAdvice.java
src/main/java/com/moa/service/UserService.java
src/test/java/com/moa/base/AbstractControllerTest.java
src/test/java/com/moa/controller/UserControllerTest.java
src/test/java/com/moa/global/filter/LoginProcessFilterTest.java
src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-fields.snippet
src/test/resources/org/springframework/restdocs/templates/asciidoctor/request-headers.snippet

#13 
UserController 테스트 진행
- 회원 가입
- 회원 탈퇴
- filter test 진행

Feat jhs 13

---

src/main/java/com/moa/controller/UserController.java
src/main/java/com/moa/domain/user/User.java
src/main/java/com/moa/dto/user/UserInfoResponse.java
src/main/java/com/moa/dto/user/UserUpdateRequest.java
src/main/java/com/moa/service/UserService.java
src/test/java/com/moa/controller/UserControllerTest.java
src/test/java/com/moa/service/UserServiceTest.java

Issue: #13 
- 사용자 정보 관련 기능 MVC 테스트

[test] 사용자 정보 관련 기능 MVC 테스트

---

src/main/java/com/moa/controller/UserController.java
src/main/java/com/moa/domain/user/User.java
src/main/java/com/moa/dto/user/UserPwUpdateRequest.java
src/main/java/com/moa/global/exception/ExceptionResponse.java
src/main/java/com/moa/global/exception/GlobalControllerAdvice.java
src/main/java/com/moa/global/exception/auth/CustomAuthException.java
src/main/java/com/moa/global/exception/auth/WrongPasswordException.java
src/main/java/com/moa/service/UserService.java
src/test/java/com/moa/controller/UserControllerTest.java
src/test/java/com/moa/service/UserServiceTest.java

Issue: #14 
- 사용자 비밀번호 수정 기능 추가 & 테스트

[feat] 사용자 비밀번호 수정 기능 추가

---

src/main/java/com/moa/controller/RecruitmentController.java
src/main/java/com/moa/controller/UserController.java
src/main/java/com/moa/domain/member/ApplimentMemberRepository.java
src/main/java/com/moa/domain/member/Approval.java
src/main/java/com/moa/domain/member/RecruitMemberRepository.java
src/main/java/com/moa/dto/StatusResponse.java
src/main/java/com/moa/dto/recruit/RecruitApplyRequest.java
src/main/java/com/moa/dto/user/UserInfoResponse.java
src/main/java/com/moa/global/auth/model/JwtUser.java
src/main/java/com/moa/global/auth/model/SecurityUser.java
src/main/java/com/moa/global/auth/utils/JwtService.java
src/main/java/com/moa/global/config/SecurityConfig.java
src/main/java/com/moa/global/config/sub/SecurityFilterBeanConfig.java
src/main/java/com/moa/global/config/sub/SecurityServiceBeanConfig.java
src/main/java/com/moa/global/filter/JwtAuthenticationFilter.java
src/main/java/com/moa/service/RecruitMemberService.java
src/main/java/com/moa/service/UserService.java
src/test/java/com/moa/base/AbstractServiceTest.java
src/test/java/com/moa/controller/UserControllerTest.java
src/test/java/com/moa/service/RecruitMemberServiceTest.java
src/test/java/com/moa/service/UserServiceTest.java

#23 
- 참여 희망 신청
- 개인 정보 조회 시 참여 희망 스터디 리스트 추가
- 모집 완료 시 알림

Feat jhs 23

---

src/main/java/com/moa/InitData.java
src/main/java/com/moa/controller/RecruitmentController.java
src/main/java/com/moa/service/RecruitmentService.java
src/test/java/com/moa/service/RecruitmentServiceTest.java

refactor: 반환값 변경

---

src/main/java/com/moa/domain/base/BaseTimeEntity.java
src/main/java/com/moa/domain/member/AttendMember.java
src/main/java/com/moa/domain/member/AttendMemberRepository.java
src/main/java/com/moa/domain/member/Attendance.java
src/main/java/com/moa/domain/notice/Notice.java
src/main/java/com/moa/domain/notice/NoticeRepository.java

feat: DB변경으로 인한 엔티티 재정의

---

src/main/java/com/moa/controller/UserController.java
src/main/java/com/moa/dto/user/EmailDuplicateRequest.java
src/main/java/com/moa/service/UserService.java
src/test/java/com/moa/service/UserServiceTest.java

feat: 이메일 중복체크 API 추가

---

build.gradle

Fix: querydsl 설정 변경

---

src/main/java/com/moa/service/graham/GrahamAlgo.java
src/test/java/com/moa/algo/GrahamAlgorithm.java

Issue: #37 
그라함 알고리즘 테스트 코드 내부 구현

test: 그라함 알고리즘 테스팅 구현

---

src/main/java/com/moa/domain/notice/Notice.java
src/main/java/com/moa/dto/notice/UpdateNoticeRequest.java
src/main/java/com/moa/dto/possible/PossibleTimeData.java
src/test/java/com/moa/service/NoticeServiceTest.java

refactor: 날짜 타입 변경

---

src/main/java/com/moa/domain/recruit/RecruitmentRepository.java
src/main/java/com/moa/dto/recruit/RecruitmentsInfo.java
src/main/java/com/moa/dto/user/UserActivityInfo.java

fix: 쿼리 조건문, 반환 값 변경
유저 정보 조회 시 반환 값 enum name 에서 status 값으로 변경
recruitmentRepo query 조건 절 변경

fix: 쿼리 조건문, 반환값 변경

---

build.gradle
src/main/java/com/moa/controller/AdminController.java
src/main/java/com/moa/controller/PossibleTimeController.java
src/main/java/com/moa/domain/member/AdminRepository.java
src/main/java/com/moa/dto/member/ApprovedMemberResponse.java
src/main/java/com/moa/service/PossibleTimeService.java
src/test/java/com/moa/service/AdminServiceTest.java

fix: 오류 수정 및 일부 응답 객체 필드 변경

---

src/main/java/com/moa/controller/AdminController.java
src/main/java/com/moa/controller/UserController.java
src/main/java/com/moa/dto/constant/RedirectURIConst.java
src/main/java/com/moa/dto/member/ApplimentMemberResponse.java
src/main/java/com/moa/dto/user/UserActivityInfo.java
src/main/java/com/moa/dto/user/UserRecruitmentInterestInfo.java
src/test/java/com/moa/service/AdminServiceTest.java

Issue: #61 
- 신청 멤버 조회시 상세 정보 관련 redirectUri 값 추가
- test 검증 값 추가

feat: 신청 멤버 조회시 상세 정보 관련 redirectUri 값 추가

---

src/main/java/com/moa/dto/recruit/RecruitInfoResponse.java

refactor: state 반환 값 변경

---

src/main/java/com/moa/domain/recruit/Recruitment.java
src/main/java/com/moa/domain/recruit/RecruitmentRepository.java
src/main/java/com/moa/domain/user/UserRepository.java
src/main/java/com/moa/dto/recruit/RecruitInfoResponse.java
src/main/java/com/moa/dto/recruit/RecruitmentInfo.java
src/main/java/com/moa/dto/recruit/RecruitmentInterestInfo.java
src/main/java/com/moa/dto/recruit/RecruitmentsInfo.java
src/main/java/com/moa/dto/user/UserRecruitmentInterestInfo.java
src/main/java/com/moa/global/filter/handler/RecruitmentAuthorizationManagerForAuthor.java
src/main/java/com/moa/service/RecruitmentService.java
src/main/java/com/moa/service/UserService.java
src/test/java/com/moa/domain/recruit/RecruitmentRepositoryTest.java
src/test/java/com/moa/service/RecruitmentServiceTest.java
src/test/java/com/moa/service/unit/UserServiceUnitTest.java

Issue: #66 
- 작성 글, 관심 글 조회 데이터 수정
- 태그 관련 N+1 문제 해결

refactor: 모집글 조회 관련 필드 변경

---

src/main/java/com/moa/domain/reply/Reply.java

feat: Reply Entity 매핑

---

src/test/java/com/moa/controller/UserControllerTest.java
src/test/java/com/moa/service/unit/UserServiceUnitTest.java

테스트 오류 수정
- UserControllerTest
- UserServiceUnitTest

test: 테스트 오류 수정

---

src/main/java/com/moa/domain/recruit/RecruitmentSearchRepository.java
src/main/java/com/moa/dto/recruit/RecruitmentInfo.java
src/test/java/com/moa/domain/recruit/RecruitmentSearchRepositoryTest.java

fix: 테스트 에러 수정

---

src/main/java/com/moa/controller/LinkController.java
src/main/java/com/moa/domain/link/Link.java
src/main/java/com/moa/domain/link/LinkRepository.java
src/main/java/com/moa/domain/user/User.java
src/main/java/com/moa/dto/user/UserInfo.java
src/main/java/com/moa/service/LinkService.java

Issue: #85 
- 엔티티 매핑
- 사용자 개인정보 반환 값 링크 추가
- 링크 추가 endPoint 기능 추가

사용자 관련 링크 기능 추가

---

src/main/java/com/moa/domain/member/RecruitMember.java
src/main/java/com/moa/dto/notice/NoticesResponse.java
src/main/java/com/moa/dto/reply/RepliesInfo.java
src/test/java/com/moa/controller/NoticeControllerUnitTest.java
src/test/java/com/moa/service/NoticeServiceTest.java
src/test/java/com/moa/service/unit/NoticeServiceUnitTest.java

Issue: #87 
- 공지사항 반환 값 변환
- 댓글 반환 값 변환
- 모집 글 삭제 시 오류 해결

반환 값 변환 및 오류 수정

---

src/main/java/com/moa/dto/PageCustomResponse.java
src/main/java/com/moa/dto/notice/NoticesResponse.java
src/main/java/com/moa/dto/reply/RepliesInfo.java

chore: 반환값 네이밍 변경

---

.github/workflows/bulid-deploy-PR.yml
.github/workflows/bulid-deploy-PUSH.yml

Issue: #95 
- action: yml 정의
- action: action trigger 분리

action: action trigger 분리

---

src/main/java/com/moa/controller/UserController.java
src/main/java/com/moa/domain/user/User.java
src/main/java/com/moa/dto/user/UserInfoUpdateRequest.java
src/main/java/com/moa/dto/user/UserProfileUpdateRequest.java
src/main/java/com/moa/global/config/SecurityConfig.java
src/main/java/com/moa/service/UserService.java
src/test/java/com/moa/controller/UserControllerTest.java

- spring secuirty endpoint 수정
- 사용자 정보 업데이트 기능 분리
사용자 프로필 이미지 S3에 저장하는 거는 제가 한번 해볼게요

추가 요구사항 수정

---

src/main/java/com/moa/global/config/SecurityConfig.java

fix: 모집글 조회 권한 변경

---

src/main/java/com/moa/domain/user/User.java
src/main/java/com/moa/dto/user/UserInfo.java

코드 충돌나는 부분에서 누락된 부분이 있어서 수정해서 올립니다

fix: 머지 과정 코드 충돌 누락 해결

---

src/main/java/com/moa/global/filter/handler/JwtProviderHandler.java

fix: return value character encoding set

fix: return value character encoding set

---

src/main/java/com/moa/global/filter/handler/JwtProviderHandler.java

fix: return value character encoding set1

fix: return value character encoding set1

---

src/main/java/com/moa/controller/UserController.java
src/main/java/com/moa/domain/member/Attendance.java
src/main/java/com/moa/domain/recruit/Recruitment.java
src/main/java/com/moa/domain/recruit/tag/RecruitTagRepository.java
src/main/java/com/moa/domain/user/User.java
src/main/java/com/moa/dto/notice/NoticesResponse.java
src/main/java/com/moa/service/RecruitmentService.java
src/main/java/com/moa/service/UserService.java
src/test/java/com/moa/controller/NoticeControllerUnitTest.java
src/test/java/com/moa/service/RecruitmentServiceTest.java

Issue: #110 
- 공지사항 전체 조회 시 참여 멤버 아이디(attendMemberId) 값 추가
- 모집 글 수정 시 recruitTag 에러 관련 수정

프론트 요구사항 수정

---

src/main/java/com/moa/dto/possible/PossibleTimeRequest.java

feat: 시간 조율 빈 배열 값 처리 추가

---

src/main/java/com/moa/domain/member/AttendMember.java
src/main/java/com/moa/domain/notice/Notice.java
src/main/java/com/moa/dto/notice/NoticesResponse.java
src/main/java/com/moa/service/AttendMemberService.java

fix: 투표 종료 조건 변경

---

src/main/java/com/moa/service/UserService.java

fix: image null 검증 로직 추가

---

src/main/java/com/moa/controller/NoticeController.java
src/main/java/com/moa/domain/notice/Notice.java
src/main/java/com/moa/dto/notice/NoticesResponse.java
src/main/java/com/moa/service/NoticeService.java
src/test/java/com/moa/controller/NoticeControllerUnitTest.java
src/test/java/com/moa/domain/notice/NoticeRepositoryTest.java
src/test/java/com/moa/service/unit/NoticeServiceUnitTest.java

변경 전 - 추천 지역 전달
변경 후 - 추천 지역이 아니라 중앙 지점 위경도값 전달
카카오 api 사용 시 중앙 위경도가 대전과 같이 다른 지역임에도 불구하고 서울로 나옴

feat: 추천 지역 기능 수정
